on: [push]

name: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - name: Install node modules
        run: yarn install --frozen-lockfile

      - name: Install wasm-pack
        run: cargo install --git https://github.com/frewsxcv/wasm-pack.git --branch patch-2
        # uses: jetli/wasm-pack-action@v0.3.0

      - name: Build
        run: yarn build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
